pabmejbui/Acme-ANS

.classpath
.project
src/main/resources/WEB-INF/views/fragments/menu-en.i18n
src/main/resources/WEB-INF/views/fragments/menu-es.i18n
src/main/resources/WEB-INF/views/fragments/menu.jsp

Modify the anonymous menu so that it shows an option that takes the browser to the home page of your favourite web site. The title must read as follows: “〈id-number〉: 〈surname〉, 〈name〉”, where “〈id-number〉” denotes your DNI, NIE, or passport number, “〈surname〉” denotes your surname/s, and “〈name〉” denotes your name/s. 
Closes #10

feat(student1): Task 1 - Modify the anonymus menu #10

---

src/main/resources/WEB-INF/views/fragments/menu-en.i18n
src/main/resources/WEB-INF/views/fragments/menu-es.i18n
src/main/resources/WEB-INF/views/fragments/menu.jsp

Modify the anonymous menu so that it shows an option that takes the browser to the home page of your favourite web site. The title must read as follows: “〈id-number〉: 〈surname〉, 〈name〉”, where “〈id-number〉” denotes your DNI, NIE, or passport number, “〈surname〉” denotes your surname/s, and “〈name〉” denotes your name/s.
Closes #15

feat(student2): Task 1 - Modify the anonymus menu #15

---

.classpath
.settings/org.eclipse.wst.common.component
src/main/resources/WEB-INF/views/fragments/menu-en.i18n
src/main/resources/WEB-INF/views/fragments/menu-es.i18n
src/main/resources/WEB-INF/views/fragments/menu.jsp

Modify the anonymous menu so that it shows an option that takes the browser to the home page of your favourite web site. The title must read as follows: “〈id-number〉: 〈surname〉, 〈name〉”, where “〈id-number〉” denotes your DNI, NIE, or passport number, “〈surname〉” denotes your surname/s, and “〈name〉” denotes your name/s.
Closes #18

feat(student5): Task 1 - Modify the anonymous menu #18

---

.project
src/main/resources/WEB-INF/views/fragments/menu-en.i18n
src/main/resources/WEB-INF/views/fragments/menu-es.i18n
src/main/resources/WEB-INF/views/fragments/menu.jsp

feat(student4): Task 1 - Modify the anonymous menu #33

---

.project

Problem caused by a link resource

fix(project): problem with .project file

---

src/main/resources/WEB-INF/views/fragments/menu-en.i18n
src/main/resources/WEB-INF/views/fragments/menu-es.i18n
src/main/resources/WEB-INF/views/fragments/menu.jsp

Student3 - Task 1 - Modify the Annonimous Menu #37

---

.classpath
.gitignore
.project
.settings/org.eclipse.wst.common.component
src/main/java/acme/entities/Airline.java
src/main/java/acme/entities/AirlineType.java
src/main/java/acme/entities/DUMMY.txt

Group - Task5 - Airline entity

---

src/main/java/acme/constraints/PassportValidator.java
src/main/java/acme/constraints/ValidPassport.java
src/main/java/acme/entities/passenger/Passenger.java

Changes:
✅ Added Passenger entity with required fields.
✅ Implemented @ValidPassport annotation.
✅ Created PassportValidator for custom validation logic.
closes #211

feat(student2): Task - 044 - Passenger entity done!

---

reports/Student #1/D02/D02 - Student1 - UML.uxf

This is the Student1 UML.
Closes #103

feat(student1): Task 027 - UML Domain model #103

---

src/main/java/acme/entities/bookings/Booking.java
src/main/java/acme/entities/bookings/TravelClass.java
src/main/java/acme/entities/customers/Customer.java
src/main/java/acme/entities/services/Service.java

✅ Added the Booking entity with necessary attributes and relationships.
✅ Removed unnecessary @NotBlank validations in Service and Customer where @Mandatory already enforces the constraint.
✅ Ensured consistency in validation logic across entities.
📢 Notes:
- The Booking entity includes relationships to Customer and Service, ensuring proper linkage in the database.
- The cleanup avoids redundant validation layers, improving maintainability.
closes #210

Task 043 booking management

---

src/main/java/acme/entities/customers/Customer.java
src/main/resources/WEB-INF/data/sample/customer.csv

✅ Added sample test data for the Customer entity.
✅ Fixed a  comma in the regular expression for Customer, ensuring correct validation.
📢 Notes:
- The sample test data allows for better testing coverage and validation of Customer-related logic.
- The regular expression fix ensures proper population.
closes #214

Task 045 sample test data

---

src/main/java/acme/constraints/PhoneValidator.java
src/main/java/acme/constraints/manager/ManagerValidator.java
src/main/java/acme/constraints/manager/ValidManager.java
src/main/java/acme/entities/airlines/Airline.java
src/main/java/acme/realms/Manager.java
src/main/resources/WEB-INF/data/sample/airline.csv
src/main/resources/WEB-INF/data/sample/manager.csv
src/main/resources/WEB-INF/data/sample/user-account.csv
src/main/resources/WEB-INF/views/messages-en.i18n
src/main/resources/WEB-INF/views/messages-es.i18n

Without realisation I made many changes and additions, during the realisation of the Task 021 - Manager Entity of the student1, that are part of another tasks, so instead of copying and deleting things, I decide to not follow the branch policy this time. I would try to do not make more pull requests like this.
Closes #241 
Closes #97 
Closes #100

feat(group,student1): This pull request contains many tasks from student1 and group requirements

---

.gitignore
.project
src/main/java/acme/constraints/customer/CustomerValidator.java
src/main/java/acme/constraints/customer/ValidCustomer.java
src/main/java/acme/realms/Customer.java
src/main/resources/WEB-INF/data/sample/customer.csv
src/main/resources/WEB-INF/data/sample/user-account.csv
src/main/resources/WEB-INF/views/authenticated/consumer/messages-en.i18n
src/main/resources/WEB-INF/views/authenticated/consumer/messages-es.i18n
src/main/resources/WEB-INF/views/messages-en.i18n
src/main/resources/WEB-INF/views/messages-es.i18n

fix(student2): review done!!

---

src/main/java/acme/entities/flightAssignment/AssignmentStatus.java
src/main/java/acme/entities/flightAssignment/DutyType.java
src/main/java/acme/entities/flightAssignment/FlightAssignment.java

Task 009 flight assignment entity

---

src/main/java/acme/entities/flightCrewMembers/AvailabilityStatus.java
src/main/java/acme/entities/flightCrewMembers/FlightCrewMember.java
src/main/java/acme/entities/flightCrewMembers/FlightCrewMembers.java

Task 010 flight crew members entity

---

src/main/java/acme/entities/bookings/Booking.java
src/main/java/acme/entities/bookings/TravelClass.java
src/main/resources/WEB-INF/data/sample/booking.csv
src/main/resources/WEB-INF/data/sample/passenger.csv

Booking entity:
✅Add relationship with Flight https://github.com/manytoone and comment it
✅Modify relationship with Passenger https://github.com/OnetoOne
✅Add Sample data csv
closes #246

fix(student2): testing requirements done!

---

src/main/java/acme/entities/flightAssignment/FlightAssignment.java
src/main/java/acme/realms/flightCrewMembers/AvailabilityStatus.java
src/main/java/acme/realms/flightCrewMembers/FlightCrewMember.java
src/main/resources/WEB-INF/data/sample/flightCrewMember.csv
src/main/resources/WEB-INF/data/sample/user-account.csv

fix(Student3): Some clasess fixed.

---

src/main/java/acme/constraints/NibbleValidator.java
src/main/java/acme/constraints/ValidNibble.java
src/main/java/acme/constraints/ValidPhone.java
src/main/java/acme/entities/bookings/Booking.java
src/main/java/acme/entities/passenger/Passenger.java
src/main/resources/WEB-INF/data/sample/booking.csv
src/main/resources/WEB-INF/data/sample/passenger.csv

✅Add some sample data.
✅Create custom validation for lastCardNibble.
closes #249

Task - 044 - R1 passenger information

---

src/main/java/acme/entities/activityLog/ActivityLog.java
src/main/java/acme/entities/flightAssignment/FlightAssignment.java
src/main/java/acme/entities/flights/Flight.java
src/main/java/acme/entities/flights/FlightRepository.java
src/main/java/acme/entities/flights/FlightService.java
src/main/java/acme/entities/flights/Indication.java
src/main/resources/WEB-INF/data/sample/flight.csv
src/main/resources/WEB-INF/views/messages-en.i18n
src/main/resources/WEB-INF/views/messages-es.i18n

feat(student1): Task 022 - Flight entity #98

---

src/main/java/acme/constraints/flights/FlightNumberValidator.java
src/main/java/acme/constraints/flights/LegValidator.java
src/main/java/acme/constraints/flights/ValidFlightNumber.java
src/main/java/acme/constraints/flights/ValidLeg.java
src/main/java/acme/entities/flightAssignment/FlightAssignment.java
src/main/java/acme/entities/flights/Leg.java
src/main/java/acme/entities/flights/LegStatus.java

feat(student1): Task 023 - Leg Entity #99

---

src/main/java/acme/entities/activityLog/ActivityLog.java

fix(Student3): Fixing relationship Activity Log.

---

src/main/java/acme/entities/activityLog/ActivityLog.java
src/main/java/acme/forms/ManagerDashboard.java

feat(student1): Task 026 - Manager dashboard #102

---

src/main/java/acme/constraints/PromoCodeValidator.java
src/main/java/acme/constraints/ValidPromoCode.java
src/main/java/acme/entities/services/Service.java
src/main/resources/WEB-INF/data/sample/service.csv

✅Delete Relationships
✅Create a sample test service.csv
✅Delete Derived attributes
✅Create validator constraint ValidPromoCode 
closes #261

fix(Group): Task -060- R1 Service Entity

---

src/main/java/acme/realms/flightCrewMembers/FlightCrewMember.java
src/main/resources/WEB-INF/data/sample/flightCrewMember.csv

feat(Student3):Task-007-SampleDataFlightCrewMember

---

src/main/java/acme/forms/AdministratorDashboard.java

feat(Student3):Task054-AdministratorDashboards-done

---

src/main/java/acme/forms/FlightCrewMemberDashboard.java

feat(Student3):FlightCrewMemberDashboard

---

src/main/java/acme/entities/airlines/Airline.java

fix(group): Task 063/R1 - Airline entity fixed #279

---

reports/Student #2/D02/D02-Student2-UML.uxf
src/main/java/acme/entities/passenger/Passenger.java
src/main/resources/WEB-INF/data/sample/passenger.csv

Done:
DraftMode en la entidad Passenger
Cambiar Tipo DATE a TIMESTAMP en año de nacimiento
Cambiar también TIMESTAMP en UML
closes #277

fix(stundet2): adding draftMode and Change TIMESTAMP type

---

reports/Student #2/D02/D02-Student2-UML.uxf
src/main/java/acme/entities/bookings/Booking.java
src/main/resources/WEB-INF/data/sample/booking.csv

done:
> draftMode en la entidad Booking
> Cambiar el csv para el amount / currency
> Descomentar relacion con flight
closes #278

fix(student2): draftMode and csv added!

---

src/main/java/acme/entities/aircrafts/Aircraft.java
src/main/java/acme/entities/airlines/Airline.java

fix(group): Task 059/R2 - Aircraft entity fixed #284

---

src/main/java/acme/constraints/flights/FlightNumberValidator.java
src/main/java/acme/entities/claims/Claim.java
src/main/java/acme/entities/flights/FlightService.java
src/main/resources/WEB-INF/views/messages-en.i18n
src/main/resources/WEB-INF/views/messages-es.i18n

fix(student1): Task 022/R1 - Flight fixes #290

---

src/main/resources/WEB-INF/data/sample/leg.csv

feat(student1): Task 023/R1 - Leg entity #292

---

src/main/java/acme/entities/services/Service.java
src/main/resources/WEB-INF/data/sample/service.csv

fix(student2): draftMode added

---

src/main/java/acme/constraints/LicenseValidator.java
src/main/java/acme/constraints/ValidLicense.java
src/main/java/acme/entitiest/technicians/Technician.java
src/main/java/acme/realms/Technician.java
src/main/resources/WEB-INF/views/messages-en.i18n
src/main/resources/WEB-INF/views/messages-es.i18n

feat(student5): Task 038 - Technician Entity

---

src/main/java/acme/entities/maintenanceRecords/MaintenanceRecord.java
src/main/java/acme/entities/maintenanceRecords/Status.java

 feat(student5): Task 041 - Maintenance Records Entity

---

src/main/java/acme/entities/maintenanceRecords/MaintenanceRecord.java
src/main/java/acme/entities/maintenanceRecords/MaintenanceRecordTask.java
src/main/java/acme/entities/maintenanceRecords/MaintenanceStatus.java
src/main/java/acme/entities/tasks/Task.java
src/main/java/acme/entities/tasks/TaskType.java
src/main/java/acme/entities/tasks/Type.java

feat(student5): Task 037 - Task Entity

---

src/main/java/acme/constraints/PassportValidator.java
src/main/java/acme/constraints/bannedPassengers/BannedPassengerValidator.java
src/main/java/acme/constraints/bannedPassengers/ValidBannedPassenger.java
src/main/java/acme/entities/bannedPassengers/BannedPassenger.java
src/main/resources/WEB-INF/data/sample/bannedPassenger.csv
src/main/resources/WEB-INF/views/messages-en.i18n
src/main/resources/WEB-INF/views/messages-es.i18n

feat(Group): Task-055-BannedPassengerService #130

---

src/main/java/acme/entities/passenger/Passenger.java

✅Cambiar tipo primitivo de Boolean ---> boolean en el draftMode Quitar @Valid
✅Comprobar que las entidades tengan solo tres niveles de validación
✅En caso de tener patrones crear un validador si no hay creado ya uno
✅Comprobar si hay atributos con TIMESTAMP quitar el @Automapped
✅Hacer una tabla intermedia entre booking y passenger, de esa tabla luego tiene relación con flight
closes #308

feat(student2): follow up changes done!

---

src/main/java/acme/entities/airlines/Airline.java
src/main/java/acme/entities/airports/Airport.java

Airline entity fixed.
Closes #302

fix(group): Task 063/R2 - Airline entity fixed #302

---

src/main/java/acme/constraints/flights/FlightNumberValidator.java
src/main/java/acme/entities/airlines/Airline.java
src/main/java/acme/entities/flights/Leg.java
src/main/java/acme/realms/Manager.java
src/main/resources/WEB-INF/data/sample/leg.csv
src/main/resources/WEB-INF/data/sample/manager.csv

fix(student1): Task 021/R1 - Manager entity #304

---

src/main/java/acme/entities/flights/Leg.java

Task 023/R2 - Leg entity #306

---

src/main/java/acme/entities/airports/Airport.java

Establecer min = 1 en Mandatory Strings.
Quitar @Automapped cuando tenemos @Column(unique = true).
Cambiar @ValidString(pattern = "^\\+?\\d{6,15}$") por @ValidPhone.
Closes #299

fix(Group): enhance validation for airport attributes

---

src/main/java/acme/entities/aircrafts/Aircraft.java

fix(group): Task 059/R3 - Aircraft entity #336

---

src/main/java/acme/entities/services/Service.java
src/main/resources/WEB-INF/data/sample/service.csv

✅Cambiar tipo primitivo de Boolean ---> boolean en el draftMode Quitar @Valid
✅Comprobar que las entidades tengan solo tres niveles de validación
✅En caso de tener patrones crear un validador si no hay creado ya uno
✅Comprobar si hay atributos con TIMESTAMP quitar el @Automapped
✅Quitar relación servicio con aeropuerto
closes #303

fix(Group): Follow up changes done

---

src/main/java/acme/constraints/LicenseValidator.java
src/main/resources/WEB-INF/data/sample/technician.csv
src/main/resources/WEB-INF/data/sample/user-account.csv

feat(student5):  Task 040 - Technician sample data

---

src/main/java/acme/entities/maintenanceRecords/MaintenanceRecord.java
src/main/resources/WEB-INF/data/sample/maintenanceRecord.csv

feat(student5): Task 041/R1 - Maintenance records entity

---

src/main/java/acme/entities/tasks/Task.java
src/main/resources/WEB-INF/data/sample/maintenanceRecordTask.csv
src/main/resources/WEB-INF/data/sample/task.csv

feat(student5): Task 037/R1 - Task entity

---

src/main/java/acme/forms/TechnicianDashboard.java

feat(student5): Task 036 - Technician dashboard

---

src/main/java/acme/entities/reviews/Review.java
src/main/resources/WEB-INF/data/sample/review.csv

feat(group): Task 031/R1 - Review Entity

---

src/main/java/acme/forms/AdministratorDashboard.java

fixed(Group): Task054-fixedDashBoard

---

src/main/resources/WEB-INF/data/sample/user-account.csv

fixed(Student3): Task007-R2-SampleDataFlightCrewMembers

---

.classpath
.gitignore
.settings/org.eclipse.wst.common.component

Task 064 new project version

---

.classpath
.gitignore
.settings/org.eclipse.wst.common.component

Task 064/R1 - New project version #387

---

.project
.settings/org.eclipse.wst.common.component
src/main/java/acme/features/recommendation/Recommendation.java

Recommendation destination board from last deliverable done!

feat(Student2): Recommendation destination board done!

---

src/main/java/acme/features/any/service/AnyServiceController.java
src/main/java/acme/features/any/service/AnyServiceRepository.java
src/main/resources/WEB-INF/views/fragments/footer.jsp

feat(student2): task 068: Operations by any principals on service #395

---

src/main/java/acme/entities/maintenanceRecords/MaintenanceRecord.java
src/main/java/acme/entities/maintenanceRecords/MaintenanceRecordTask.java
src/main/java/acme/entities/tasks/Task.java

fix(student5): update entities from Follow-up feedback

---

src/main/java/acme/entities/reviews/Review.java

fix(group):fix Review entity relationship constraints

---

src/main/java/acme/features/manager/flight/ManagerFlightCreateService.java
src/main/java/acme/features/manager/flight/ManagerFlightListService.java
src/main/java/acme/features/manager/flight/ManagerFlightRepository.java
src/main/java/acme/features/manager/flight/ManagerFlightShowService.java
src/main/resources/WEB-INF/views/manager/flight/list.jsp
src/main/resources/WEB-INF/views/manager/flight/messages-en.i18n
src/main/resources/WEB-INF/views/manager/flight/messages-es.i18n
src/main/resources/WEB-INF/views/messages-en.i18n
src/main/resources/WEB-INF/views/messages-es.i18n

- I have modified the authorise method on the show service to not allow front hacking as it has been suggested in the follow up.
- As well, in the follow up, the professor recommended me to validate the supported currencys of the system. So it has been done in this
Closes #536

fix(student1): fixing Task 082 - Follow Up. #536

---

.classpath
.settings/org.eclipse.wst.common.component
src/main/java/acme/features/any/service/AnyServiceRepository.java
src/main/java/acme/features/customer/booking/CustomerBookingController.java
src/main/java/acme/features/customer/booking/CustomerBookingCreateService.java
src/main/java/acme/features/customer/booking/CustomerBookingListService.java
src/main/java/acme/features/customer/booking/CustomerBookingRepository.java
src/main/java/acme/features/customer/booking/CustomerBookingShowService.java
src/main/java/acme/features/customer/booking/CustomerBookingUpdateService.java
src/main/resources/WEB-INF/data/sample/service.csv
src/main/resources/WEB-INF/views/customer/booking/form.jsp
src/main/resources/WEB-INF/views/customer/booking/list.jsp
src/main/resources/WEB-INF/views/customer/booking/messages-en.i18n
src/main/resources/WEB-INF/views/customer/booking/messages-es.i18n
src/main/resources/WEB-INF/views/fragments/menu-en.i18n
src/main/resources/WEB-INF/views/fragments/menu-es.i18n
src/main/resources/WEB-INF/views/fragments/menu.jsp

Task 094 operations by customers on bookings

---

src/main/resources/WEB-INF/data/sample/activityLog.csv
src/main/resources/WEB-INF/data/sample/flightAssignment.csv
src/main/resources/WEB-INF/data/sample/flightCrewMember.csv
src/main/resources/WEB-INF/data/sample/user-account.csv
src/main/resources/application.properties

hotfix:Sampledata

---

src/main/java/acme/constraints/ValidLocatorCode.java
src/main/java/acme/constraints/bookings/BookingValidator.java
src/main/java/acme/constraints/bookings/ValidBooking.java
src/main/java/acme/constraints/customer/CustomerValidator.java
src/main/java/acme/entities/bookings/Booking.java
src/main/java/acme/entities/bookings/BookingRepository.java
src/main/java/acme/features/customer/booking/CustomerBookingController.java
src/main/java/acme/features/customer/booking/CustomerBookingCreateService.java
src/main/java/acme/features/customer/booking/CustomerBookingListService.java
src/main/java/acme/features/customer/booking/CustomerBookingRepository.java
src/main/java/acme/features/customer/booking/CustomerBookingShowService.java
src/main/java/acme/features/customer/booking/CustomerBookingUpdateService.java
src/main/java/acme/realms/customer/Customer.java
src/main/java/acme/realms/customer/CustomerRepository.java
src/main/resources/WEB-INF/data/sample/booking.csv
src/main/resources/WEB-INF/data/sample/customer.csv
src/main/resources/WEB-INF/data/sample/user-account.csv
src/main/resources/WEB-INF/views/customer/booking/form.jsp
src/main/resources/WEB-INF/views/customer/booking/messages-en.i18n
src/main/resources/WEB-INF/views/customer/booking/messages-es.i18n
src/main/resources/WEB-INF/views/messages-en.i18n
src/main/resources/WEB-INF/views/messages-es.i18n

Task 094 R1 operations by customers on bookings

---

.classpath
.project
.settings/org.eclipse.wst.common.component
src/main/java/acme/constraints/PromoCodeValidator.java
src/main/java/acme/constraints/ValidPromoCode.java
src/main/java/acme/entities/services/Service.java
src/main/java/acme/features/administrator/service/AdministratorServiceController.java
src/main/java/acme/features/administrator/service/AdministratorServiceCreateService.java
src/main/java/acme/features/administrator/service/AdministratorServiceDeleteService.java
src/main/java/acme/features/administrator/service/AdministratorServiceListService.java
src/main/java/acme/features/administrator/service/AdministratorServiceRepository.java
src/main/java/acme/features/administrator/service/AdministratorServiceShowService.java
src/main/java/acme/features/administrator/service/AdministratorServiceUpdateService.java
src/main/resources/WEB-INF/data/sample/service.csv
src/main/resources/WEB-INF/views/administrator/service/form.jsp
src/main/resources/WEB-INF/views/administrator/service/list.jsp
src/main/resources/WEB-INF/views/administrator/service/messages-en.i18n
src/main/resources/WEB-INF/views/administrator/service/messages-es.i18n
src/main/resources/WEB-INF/views/fragments/footer.jsp
src/main/resources/WEB-INF/views/fragments/menu-en.i18n
src/main/resources/WEB-INF/views/fragments/menu-es.i18n
src/main/resources/WEB-INF/views/fragments/menu.jsp
src/main/resources/WEB-INF/views/messages-en.i18n
src/main/resources/WEB-INF/views/messages-es.i18n

Task 073 operations by administrators on services

---

src/main/java/acme/components/AdvertisementController.java
src/main/java/acme/components/AdvertisementRepository.java

changing routes like the teachers ppt
closes #567

fix(Group): fixing routes for advertisement

---

src/main/java/acme/features/authenticated/manager/AuthenticatedManagerController.java
src/main/java/acme/features/authenticated/manager/AuthenticatedManagerCreateService.java
src/main/java/acme/features/authenticated/manager/AuthenticatedManagerRepository.java
src/main/java/acme/features/authenticated/manager/AuthenticatedManagerUpdateService.java
src/main/resources/WEB-INF/views/authenticated/manager/form.jsp
src/main/resources/WEB-INF/views/authenticated/manager/messages-en.i18n
src/main/resources/WEB-INF/views/authenticated/manager/messages-es.i18n
src/main/resources/WEB-INF/views/fragments/menu-en.i18n
src/main/resources/WEB-INF/views/fragments/menu-es.i18n
src/main/resources/WEB-INF/views/fragments/menu.jsp

feat(student1): Task 085 - Operations by anonymous on user accounts #430

---

src/main/java/acme/features/any/flight/AnyFlightController.java
src/main/java/acme/features/any/flight/AnyFlightListService.java
src/main/java/acme/features/any/flight/AnyFlightRepository.java
src/main/java/acme/features/any/flight/AnyFlightShowService.java
src/main/resources/WEB-INF/views/administrator/airline/messages-en.i18n
src/main/resources/WEB-INF/views/any/flight/form.jsp
src/main/resources/WEB-INF/views/any/flight/list.jsp
src/main/resources/WEB-INF/views/any/flight/messages-en.i18n
src/main/resources/WEB-INF/views/any/flight/messages-es.i18n
src/main/resources/WEB-INF/views/fragments/menu-en.i18n
src/main/resources/WEB-INF/views/fragments/menu-es.i18n
src/main/resources/WEB-INF/views/fragments/menu.jsp

feat(student1): Task 087 - Operations by any principals on flights #434

---

src/main/java/acme/features/manager/managerDashboard/ManagerDashboardController.java
src/main/java/acme/features/manager/managerDashboard/ManagerDashboardRepository.java
src/main/java/acme/features/manager/managerDashboard/ManagerDashboardShowService.java
src/main/resources/WEB-INF/views/fragments/menu-en.i18n
src/main/resources/WEB-INF/views/fragments/menu-es.i18n
src/main/resources/WEB-INF/views/fragments/menu.jsp
src/main/resources/WEB-INF/views/manager/manager-dashboard/form.jsp
src/main/resources/WEB-INF/views/manager/manager-dashboard/messages-en.i18n
src/main/resources/WEB-INF/views/manager/manager-dashboard/messages-es.i18n

feat(student1): Task 88 - Operations by managers on manager dashboards #436

---

src/main/java/acme/entities/weather/WeatherCondition.java
src/main/java/acme/entities/weather/WeatherConditionRepository.java
src/main/java/acme/entities/weather/WeatherController.java
src/main/java/acme/entities/weather/WeatherResponse.java
src/main/java/acme/entities/weather/WeatherService.java
src/main/java/acme/features/any/flightUnderBadWeather/AnyFlightUnderBadWeatherController.java
src/main/java/acme/features/any/flightUnderBadWeather/AnyFlightUnderBadWeatherListService.java
src/main/java/acme/features/any/flightUnderBadWeather/AnyFlightUnderBadWeatherRepository.java
src/main/java/acme/features/any/weather/AnyWeatherController.java
src/main/java/acme/features/any/weather/AnyWeatherListService.java
src/main/java/acme/features/any/weather/AnyWeatherRepository.java
src/main/java/acme/features/any/weather/AnyWeatherShowService.java
src/main/resources/WEB-INF/views/any/flight-under-bad-weather/list.jsp
src/main/resources/WEB-INF/views/any/flight-under-bad-weather/messages-en.i18n
src/main/resources/WEB-INF/views/any/flight-under-bad-weather/messages-es.i18n
src/main/resources/WEB-INF/views/any/weather-condition/form.jsp
src/main/resources/WEB-INF/views/any/weather-condition/list.jsp
src/main/resources/WEB-INF/views/any/weather-condition/messages-en.i18n
src/main/resources/WEB-INF/views/any/weather-condition/messages-es.i18n
src/main/resources/WEB-INF/views/fragments/menu-en.i18n
src/main/resources/WEB-INF/views/fragments/menu-es.i18n
src/main/resources/WEB-INF/views/fragments/menu.jsp

feat(student1): Task 090 - Operations by any on weather conditions #440

---

src/main/java/acme/features/administrator/booking/AdministratorBookingController.java
src/main/java/acme/features/administrator/booking/AdministratorBookingListService.java
src/main/java/acme/features/administrator/booking/AdministratorBookingRepository.java
src/main/java/acme/features/administrator/booking/AdministratorBookingShowService.java
src/main/resources/WEB-INF/views/administrator/booking/form.jsp
src/main/resources/WEB-INF/views/administrator/booking/list.jsp
src/main/resources/WEB-INF/views/administrator/booking/messages-en.i18n
src/main/resources/WEB-INF/views/administrator/booking/messages-es.i18n
src/main/resources/WEB-INF/views/authenticated/customer/messages-en.i18n
src/main/resources/WEB-INF/views/authenticated/customer/messages-es.i18n
src/main/resources/WEB-INF/views/customer/booking/messages-en.i18n
src/main/resources/WEB-INF/views/customer/booking/messages-es.i18n
src/main/resources/WEB-INF/views/fragments/menu-en.i18n
src/main/resources/WEB-INF/views/fragments/menu-es.i18n
src/main/resources/WEB-INF/views/fragments/menu.jsp

Task 099 operations by administrators on bookings

---

src/main/java/acme/entities/bookings/Booking.java
src/main/java/acme/entities/bookings/BookingRecord.java
src/main/java/acme/entities/passenger/Passenger.java
src/main/java/acme/realms/customer/Customer.java

Task 143 create appropriate indices for entities

---

src/main/java/acme/entities/maintenanceRecords/MaintenanceRecord.java
src/main/java/acme/entities/maintenanceRecords/MaintenanceRecordTask.java
src/main/java/acme/entities/tasks/Task.java
src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordController.java
src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordCreateService.java
src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordDeleteService.java
src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordListService.java
src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordPublishService.java
src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordRepository.java
src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordShowService.java
src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordUpdateService.java
src/main/java/acme/features/technician/maintenanceRecordTask/TechnicianMaintenanceRecordTasksController.java
src/main/java/acme/features/technician/maintenanceRecordTask/TechnicianMaintenanceRecordTasksCreateService.java
src/main/java/acme/features/technician/maintenanceRecordTask/TechnicianMaintenanceRecordTasksDeleteService.java
src/main/java/acme/features/technician/maintenanceRecordTask/TechnicianMaintenanceRecordTasksRepository.java
src/main/java/acme/features/technician/task/TechnicianMaintenanceRecordTasksListService.java
src/main/java/acme/features/technician/task/TechnicianTaskController.java
src/main/java/acme/features/technician/task/TechnicianTaskCreateService.java
src/main/java/acme/features/technician/task/TechnicianTaskDeleteService.java
src/main/java/acme/features/technician/task/TechnicianTaskListService.java
src/main/java/acme/features/technician/task/TechnicianTaskPublishService.java
src/main/java/acme/features/technician/task/TechnicianTaskRepository.java
src/main/java/acme/features/technician/task/TechnicianTaskShowService.java
src/main/java/acme/features/technician/task/TechnicianTaskUpdateService.java
src/main/java/acme/realms/technician/Technician.java

feeat(student5): add indices

---

src/main/java/acme/entities/activityLog/ActivityLog.java
src/main/java/acme/entities/flightAssignment/FlightAssignment.java

161-CreateAppropiateIndicesForYourEntitiesIfRequired.

feat(Student3): Task161-CreateAppropiateIndicesForYourEntitiesIfRequired.

---

src/main/resources/WEB-INF/data/sample/aircraft.csv
src/main/resources/WEB-INF/data/sample/airline.csv
src/main/resources/WEB-INF/data/sample/airport.csv
src/main/resources/WEB-INF/data/sample/flight.csv
src/main/resources/WEB-INF/data/sample/leg.csv

Task 188 modification of csvs

---

src/main/java/acme/features/customer/booking/CustomerBookingRepository.java
src/main/java/acme/features/customer/passenger/CustomerPassengerCreateService.java
src/main/java/acme/features/customer/passenger/CustomerPassengerPublishService.java
src/main/java/acme/features/customer/passenger/CustomerPassengerRepository.java
src/main/java/acme/features/customer/passenger/CustomerPassengerUpdateService.java
src/main/resources/WEB-INF/data/sample/booking.csv
src/main/resources/WEB-INF/data/sample/passenger.csv
src/main/resources/WEB-INF/views/customer/passenger/messages-en.i18n
src/main/resources/WEB-INF/views/customer/passenger/messages-es.i18n

Task 204 prevent duplicate passengers

---

src/main/java/acme/entities/recomendations/Recommendation.java
src/main/java/acme/features/administrator/recommendation/AdministratorRecommendationInitialiseController.java
src/main/java/acme/features/administrator/recommendation/AdministratorRecommendationRepository.java
src/main/java/acme/features/customer/bookingRecord/CustomerBookingRecordRepository.java
src/main/java/acme/features/customer/recomendation/CustomerRecommendationController.java
src/main/java/acme/features/customer/recomendation/CustomerRecommendationListService.java
src/main/java/acme/features/customer/recomendation/CustomerRecommendationRepository.java
src/main/java/acme/features/customer/recomendation/CustomerRecommendationShowService.java
src/main/resources/WEB-INF/data/sample/flight.csv
src/main/resources/WEB-INF/views/customer/recommendation/form.jsp
src/main/resources/WEB-INF/views/customer/recommendation/list.jsp
src/main/resources/WEB-INF/views/customer/recommendation/messages-en.i18n
src/main/resources/WEB-INF/views/customer/recommendation/messages-es.i18n
src/main/resources/WEB-INF/views/fragments/menu-en.i18n
src/main/resources/WEB-INF/views/fragments/menu-es.i18n
src/main/resources/WEB-INF/views/fragments/menu.jsp

Introduces a new feature to the administrator panel that allows for the population of Point of Interest (POI) recommendations for airports by consuming external APIs.
The new functionality:
- Integrates with the Nominatim and Overpass APIs to fetch real-world location data.
- Includes a mock data generation option for development and testing environments.
- Adds a limit to the number of recommendations fetched per city to optimize performance.
- This streamlines the process of adding real, relevant recommendations to our database.

feat: customer recommendations done!

---

src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogCreateService.java
src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogRepository.java
src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogShowService.java

fix(Student3): Task 223 - Fixing the bugs in task 9 #790

---

src/main/resources/WEB-INF/views/manager/flight/form.jsp
src/main/resources/WEB-INF/views/manager/leg/form.jsp

A modification has been made to the leg and flight form.jsp.

Task 200 - Bug in the "my legs" button of the create form #748

---

src/main/java/acme/entities/bookings/Booking.java
src/main/java/acme/entities/bookings/BookingRecord.java
src/main/java/acme/entities/passenger/Passenger.java
src/main/java/acme/realms/customer/Customer.java

fix: indexes updated

---

src/main/java/acme/entities/activityLog/ActivityLog.java
src/main/java/acme/entities/flightAssignment/FlightAssignment.java

fix(Student3): Task-270-Fixing indices
